/**
 * Lá số mẫu đối chiếu — khóa kết quả engine (Cục nạp âm cung Mệnh, Tuần lục giáp, Triệt theo Can)
 * Chạy: npm run verify
 */
export interface VerifiedCase {
  id: string;
  moTa: string;
  hoTen: string;
  gioiTinh: 'Nam' | 'Nữ';
  solar: { y: number; m: number; d: number };
  gioSinh: number;
  useLapXuan?: boolean;
  /** Ghi đè âm lịch khi cần (vd. mùng 1 Giáp Tý) */
  amLich?: { year: number; month: number; day: number; isLeapMonth?: boolean };
  expected: {
    canNam: string;
    chiNam: string;
    cuc: string;
    cungMenhDiaChi: string;
    tuan: [string, string];
    triet: [string, string];
  };
}

export const VERIFIED_CASES: VerifiedCase[] = [
  {
    id: 'giap-ty-ty-ty',
    moTa: 'Giáp Tý 1984, Nam, mùng 1 tháng Giêng giờ Tý',
    hoTen: 'Mẫu Giáp Tý',
    gioiTinh: 'Nam',
    solar: { y: 1984, m: 2, d: 2 },
    gioSinh: 0,
    amLich: { year: 1984, month: 1, day: 1 },
    expected: {
      canNam: 'Giáp',
      chiNam: 'Tý',
      cuc: 'Hỏa Lục Cục',
      cungMenhDiaChi: 'Dần',
      tuan: ['Tuất', 'Hợi'],
      triet: ['Thân', 'Dậu'],
    },
  },
  {
    id: 'canh-ngo-1990',
    moTa: 'Canh Ngọ 1990, Nam, 15/8 dương giờ Ngọ',
    hoTen: 'Mẫu Canh Ngọ',
    gioiTinh: 'Nam',
    solar: { y: 1990, m: 8, d: 15 },
    gioSinh: 6,
    expected: {
      canNam: 'Canh',
      chiNam: 'Ngọ',
      cuc: 'Hỏa Lục Cục',
      cungMenhDiaChi: 'Sửu',
      tuan: ['Tuất', 'Hợi'],
      triet: ['Ngọ', 'Mùi'],
    },
  },
  {
    id: 'at-suu-1985',
    moTa: 'Ất Sửu 1985, Nữ, 20/3/1985 giờ Dần',
    hoTen: 'Mẫu Ất Sửu',
    gioiTinh: 'Nữ',
    solar: { y: 1985, m: 3, d: 20 },
    gioSinh: 2,
    expected: {
      canNam: 'Ất',
      chiNam: 'Sửu',
      cuc: 'Hỏa Lục Cục',
      cungMenhDiaChi: 'Tý',
      tuan: ['Tuất', 'Hợi'],
      triet: ['Ngọ', 'Mùi'],
    },
  },
  {
    id: 'lap-xuan-1990',
    moTa: 'Trước Lập xuân 1990 → Can Chi năm Kỷ Tỵ',
    hoTen: 'Trước LX 1990',
    gioiTinh: 'Nam',
    solar: { y: 1990, m: 1, d: 15 },
    gioSinh: 0,
    useLapXuan: true,
    expected: {
      canNam: 'Kỷ',
      chiNam: 'Tỵ',
      cuc: 'Thủy Nhị Cục',
      cungMenhDiaChi: 'Sửu',
      tuan: ['Tuất', 'Hợi'],
      triet: ['Thân', 'Dậu'],
    },
  },
  {
    id: 'binh-dan-1986',
    moTa: 'Bính Dần 1986, Nam, 9/5/1986 giờ Thìn',
    hoTen: 'Mẫu Bính Dần',
    gioiTinh: 'Nam',
    solar: { y: 1986, m: 5, d: 9 },
    gioSinh: 4,
    expected: {
      canNam: 'Bính',
      chiNam: 'Dần',
      cuc: 'Thổ Ngũ Cục',
      cungMenhDiaChi: 'Tý',
      tuan: ['Tuất', 'Hợi'],
      triet: ['Thìn', 'Tỵ'],
    },
  },
  {
    id: 'nham-than-1992',
    moTa: 'Nhâm Thân 1992, Nữ, 1/7/1992 giờ Mùi',
    hoTen: 'Mẫu Nhâm Thân',
    gioiTinh: 'Nữ',
    solar: { y: 1992, m: 7, d: 1 },
    gioSinh: 7,
    expected: {
      canNam: 'Nhâm',
      chiNam: 'Thân',
      cuc: 'Mộc Tam Cục',
      cungMenhDiaChi: 'Tý',
      tuan: ['Tuất', 'Hợi'],
      triet: ['Dần', 'Mão'],
    },
  },
  {
    id: 'giap-tuat-1994',
    moTa: 'Giáp Tuất 1994, Nam, 10/10/1994 giờ Dậu',
    hoTen: 'Mẫu Giáp Tuất',
    gioiTinh: 'Nam',
    solar: { y: 1994, m: 10, d: 10 },
    gioSinh: 9,
    expected: {
      canNam: 'Giáp',
      chiNam: 'Tuất',
      cuc: 'Thủy Nhị Cục',
      cungMenhDiaChi: 'Sửu',
      tuan: ['Thân', 'Dậu'],
      triet: ['Thân', 'Dậu'],
    },
  },
  {
    id: 'tan-mui-1991',
    moTa: 'Tân Mùi 1991, Nữ, 8/8/1991 giờ Tỵ',
    hoTen: 'Mẫu Tân Mùi',
    gioiTinh: 'Nữ',
    solar: { y: 1991, m: 8, d: 8 },
    gioSinh: 5,
    expected: {
      canNam: 'Tân',
      chiNam: 'Mùi',
      cuc: 'Mộc Tam Cục',
      cungMenhDiaChi: 'Dần',
      tuan: ['Tuất', 'Hợi'],
      triet: ['Thìn', 'Tỵ'],
    },
  },
  {
    id: 'dinh-mao-1987',
    moTa: 'Đinh Mão 1987, Nữ, 12/4/1987 giờ Mão',
    hoTen: 'Mẫu Đinh Mão',
    gioiTinh: 'Nữ',
    solar: { y: 1987, m: 4, d: 12 },
    gioSinh: 3,
    expected: {
      canNam: 'Đinh',
      chiNam: 'Mão',
      cuc: 'Mộc Tam Cục',
      cungMenhDiaChi: 'Sửu',
      tuan: ['Tuất', 'Hợi'],
      triet: ['Dần', 'Mão'],
    },
  },
  {
    id: 'mau-thin-1988',
    moTa: 'Mậu Thìn 1988, Nam, 6/6/1988 giờ Ngọ',
    hoTen: 'Mẫu Mậu Thìn',
    gioiTinh: 'Nam',
    solar: { y: 1988, m: 6, d: 6 },
    gioSinh: 6,
    expected: {
      canNam: 'Mậu',
      chiNam: 'Thìn',
      cuc: 'Thủy Nhị Cục',
      cungMenhDiaChi: 'Hợi',
      tuan: ['Tuất', 'Hợi'],
      triet: ['Tý', 'Sửu'],
    },
  },
  {
    id: 'mau-thin-1989',
    moTa: 'Mậu Thìn 1989, Nữ, 25/1/1989 giờ Tý (trước Tết)',
    hoTen: 'Mẫu Mậu Thìn',
    gioiTinh: 'Nữ',
    solar: { y: 1989, m: 1, d: 25 },
    gioSinh: 0,
    expected: {
      canNam: 'Mậu',
      chiNam: 'Thìn',
      cuc: 'Kim Tứ Cục',
      cungMenhDiaChi: 'Sửu',
      tuan: ['Tuất', 'Hợi'],
      triet: ['Tý', 'Sửu'],
    },
  },
  {
    id: 'quy-dau-1993',
    moTa: 'Quý Dậu 1993, Nam, 18/9/1993 giờ Thân',
    hoTen: 'Mẫu Quý Dậu',
    gioiTinh: 'Nam',
    solar: { y: 1993, m: 9, d: 18 },
    gioSinh: 8,
    expected: {
      canNam: 'Quý',
      chiNam: 'Dậu',
      cuc: 'Kim Tứ Cục',
      cungMenhDiaChi: 'Sửu',
      tuan: ['Tuất', 'Hợi'],
      triet: ['Tý', 'Sửu'],
    },
  },
  {
    id: 'nham-ngo-2002',
    moTa: 'Nhâm Ngọ 2002, Nam, 3/6/2002 giờ Sửu',
    hoTen: 'Mẫu Nhâm Ngọ',
    gioiTinh: 'Nam',
    solar: { y: 2002, m: 6, d: 3 },
    gioSinh: 1,
    expected: {
      canNam: 'Nhâm',
      chiNam: 'Ngọ',
      cuc: 'Hỏa Lục Cục',
      cungMenhDiaChi: 'Thìn',
      tuan: ['Thân', 'Dậu'],
      triet: ['Dần', 'Mão'],
    },
  },
  {
    id: 'canh-thin-2000',
    moTa: 'Canh Thìn 2000, Nữ, 14/2/2000 giờ Dần',
    hoTen: 'Mẫu Canh Thìn',
    gioiTinh: 'Nữ',
    solar: { y: 2000, m: 2, d: 14 },
    gioSinh: 2,
    expected: {
      canNam: 'Canh',
      chiNam: 'Thìn',
      cuc: 'Hỏa Lục Cục',
      cungMenhDiaChi: 'Tý',
      tuan: ['Thân', 'Dậu'],
      triet: ['Ngọ', 'Mùi'],
    },
  },
  {
    id: 'at-hoi-1995',
    moTa: 'Ất Hợi 1995, Nam, 1/2/1995 giờ Hợi',
    hoTen: 'Mẫu Ất Hợi',
    gioiTinh: 'Nam',
    solar: { y: 1995, m: 2, d: 1 },
    gioSinh: 11,
    expected: {
      canNam: 'Ất',
      chiNam: 'Hợi',
      cuc: 'Thổ Ngũ Cục',
      cungMenhDiaChi: 'Mão',
      tuan: ['Thân', 'Dậu'],
      triet: ['Ngọ', 'Mùi'],
    },
  },
  {
    id: 'binh-tuat-2006',
    moTa: 'Bính Tuất 2006, Nữ, 20/11/2006 giờ Tỵ',
    hoTen: 'Mẫu Bính Tuất',
    gioiTinh: 'Nữ',
    solar: { y: 2006, m: 11, d: 20 },
    gioSinh: 5,
    expected: {
      canNam: 'Bính',
      chiNam: 'Tuất',
      cuc: 'Thủy Nhị Cục',
      cungMenhDiaChi: 'Tỵ',
      tuan: ['Ngọ', 'Mùi'],
      triet: ['Thìn', 'Tỵ'],
    },
  },
  {
    id: 'dinh-dau-1957',
    moTa: 'Đinh Dậu 1957, Nam, 8/8/1957 giờ Mùi',
    hoTen: 'Mẫu Đinh Dậu',
    gioiTinh: 'Nam',
    solar: { y: 1957, m: 8, d: 8 },
    gioSinh: 7,
    expected: {
      canNam: 'Đinh',
      chiNam: 'Dậu',
      cuc: 'Mộc Tam Cục',
      cungMenhDiaChi: 'Sửu',
      tuan: ['Thìn', 'Tỵ'],
      triet: ['Dần', 'Mão'],
    },
  },
  {
    id: 'mau-tuat-1958',
    moTa: 'Mậu Tuất 1958, Nữ, 5/5/1958 giờ Thìn',
    hoTen: 'Mẫu Mậu Tuất',
    gioiTinh: 'Nữ',
    solar: { y: 1958, m: 5, d: 5 },
    gioSinh: 4,
    expected: {
      canNam: 'Mậu',
      chiNam: 'Tuất',
      cuc: 'Kim Tứ Cục',
      cungMenhDiaChi: 'Tý',
      tuan: ['Thìn', 'Tỵ'],
      triet: ['Tý', 'Sửu'],
    },
  },
  {
    id: 'canh-ty-1961',
    moTa: 'Canh Tý 1961, Nam, 15/2/1961 giờ Ngọ',
    hoTen: 'Mẫu Canh Tý',
    gioiTinh: 'Nam',
    solar: { y: 1961, m: 2, d: 15 },
    gioSinh: 6,
    expected: {
      canNam: 'Canh',
      chiNam: 'Tý',
      cuc: 'Mộc Tam Cục',
      cungMenhDiaChi: 'Mùi',
      tuan: ['Thìn', 'Tỵ'],
      triet: ['Ngọ', 'Mùi'],
    },
  },
  {
    id: 'tan-ty-2001',
    moTa: 'Tân Tỵ 2001, Nữ, 30/4/2001 giờ Dậu',
    hoTen: 'Mẫu Tân Tỵ',
    gioiTinh: 'Nữ',
    solar: { y: 2001, m: 4, d: 30 },
    gioSinh: 9,
    expected: {
      canNam: 'Tân',
      chiNam: 'Tỵ',
      cuc: 'Hỏa Lục Cục',
      cungMenhDiaChi: 'Thân',
      tuan: ['Thân', 'Dậu'],
      triet: ['Thìn', 'Tỵ'],
    },
  },
];
